import './globals.css';
import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Playfair_Display as PlayfairDisplay, Roboto, Montserrat } from 'next/font/google';
import Providers from '@/providers';
import Header from './components/header';

const playfairDisplay = PlayfairDisplay({
  subsets: ['latin'],
  variable: '--font-playfairDisplay',
});

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-roboto',
});

const montserrat = Montserrat({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${playfairDisplay.variable} ${roboto.variable} ${montserrat.variable} font-roboto`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
